services:
  - type: web
    name: resume-rag-chatbot
    env: docker
    region: ohio
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
